"""removed pin_trycount

Revision ID: 1adecfcdfd9a
Revises: 251588c4b410
Create Date: 2020-04-19 16:53:21.486266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1adecfcdfd9a'
down_revision = '251588c4b410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managedhost', 'pin_trycount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managedhost', sa.Column('pin_trycount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
