"""removed unique from email

Revision ID: 1d3c65cbeff5
Revises: 83dd2c5664e8
Create Date: 2020-06-05 17:35:28.293680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3c65cbeff5'
down_revision = '83dd2c5664e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_manager_email', table_name='manager')
    op.create_index(op.f('ix_manager_email'), 'manager', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manager_email'), table_name='manager')
    op.create_index('ix_manager_email', 'manager', ['email'], unique=True)
    # ### end Alembic commands ###
