"""auth_lastsuccess recreated

Revision ID: 251588c4b410
Revises: f193e2b30602
Create Date: 2020-04-19 16:14:04.227824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251588c4b410'
down_revision = 'f193e2b30602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managedhost', sa.Column('auth_lastsuccess', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managedhost', 'auth_lastsuccess')
    # ### end Alembic commands ###
