"""added index for manager.pin

Revision ID: 83dd2c5664e8
Revises: 1adecfcdfd9a
Create Date: 2020-04-21 17:52:04.220211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dd2c5664e8'
down_revision = '1adecfcdfd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_managedhost_pin'), 'managedhost', ['pin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managedhost_pin'), table_name='managedhost')
    # ### end Alembic commands ###
